Repository dfinity/sdk, pull requests merged in 2022-12, with the labels that each got.

#2787 feat: Add --argument-file option to dfx canister sign
  CHANGELOG.md
  docs/cli-reference/dfx-canister.md
  e2e/tests-dfx/sign_send.bash
  src/dfx/src/commands/canister/call.rs
  src/dfx/src/commands/canister/sign.rs
  src/dfx/src/util/mod.rs
Labels: cla:agreed

#2699 chore: Change update-frontend-canister.sh to use Docker
  .dockerignore
  .github/CONTRIBUTING.md
  .github/workflows/build-frontend-canister-dummy.yml
  .github/workflows/build-frontend-canister.yml
  CHANGELOG.md
  rust-toolchain.toml
  scripts/update-frontend-canister.Dockerfile
  scripts/update-frontend-canister.sh
  src/distributed/assetstorage.wasm.gz
Labels: automerge-squash

#2797 chore: fix CI break for skipped frontend canister check
  .github/workflows/build-frontend-canister-dummy.yml
Labels: automerge-squash

#2804 chore: Update Rust to 1.65.0
  .github/workflows/e2e.yml
  .github/workflows/fmt.yml
  .github/workflows/lint.yml
  .github/workflows/prepare-dfx-assets.yml
  .github/workflows/publish.yml
  .github/workflows/unit.yml
  .github/workflows/update-docs.yml
  rust-toolchain.toml
  scripts/workflows/audit-matrix.py
  scripts/workflows/e2e-matrix.py
  src/canisters/frontend/ic-asset/src/asset_canister/batch.rs
  src/canisters/frontend/ic-asset/src/asset_config.rs
  src/canisters/frontend/ic-asset/src/plumbing.rs
  src/dfx/src/actors/btc_adapter.rs
  src/dfx/src/actors/canister_http_adapter.rs
  src/dfx/src/actors/emulator.rs
  src/dfx/src/actors/icx_proxy.rs
  src/dfx/src/actors/mod.rs
  src/dfx/src/actors/replica.rs
  src/dfx/src/commands/canister/call.rs
  src/dfx/src/commands/canister/send.rs
  src/dfx/src/commands/canister/sign.rs
  src/dfx/src/commands/new.rs
  src/dfx/src/commands/remote/generate_binding.rs
  src/dfx/src/commands/replica.rs
  src/dfx/src/commands/start.rs
  src/dfx/src/config/dfinity.rs
  src/dfx/src/lib/bitcoin/adapter/config.rs
  src/dfx/src/lib/builders/assets.rs
  src/dfx/src/lib/builders/custom.rs
  src/dfx/src/lib/builders/mod.rs
  src/dfx/src/lib/builders/motoko.rs
  src/dfx/src/lib/canister_http/adapter/config.rs
  src/dfx/src/lib/canister_info.rs
  src/dfx/src/lib/canister_info/motoko.rs
  src/dfx/src/lib/dist.rs
  src/dfx/src/lib/environment.rs
  src/dfx/src/lib/identity/identity_manager.rs
  src/dfx/src/lib/identity/identity_utils.rs
  src/dfx/src/lib/identity/keyring_mock.rs
  src/dfx/src/lib/identity/mod.rs
  src/dfx/src/lib/manifest.rs
  src/dfx/src/lib/models/canister.rs
  src/dfx/src/lib/models/canister_id_store.rs
  src/dfx/src/lib/network/directory.rs
  src/dfx/src/lib/network/local_server_descriptor.rs
  src/dfx/src/lib/network/network_descriptor.rs
  src/dfx/src/lib/nns/install_nns.rs
  src/dfx/src/lib/operations/canister/install_canister.rs
  src/dfx/src/lib/operations/canister/mod.rs
  src/dfx/src/lib/project/import.rs
  src/dfx/src/lib/sign/sign_transport.rs
  src/dfx/src/lib/wasm/file.rs
  src/dfx/src/main.rs
  src/dfx/src/util/mod.rs
  src/dfx/src/util/network.rs
Labels: automerge-squash

#2776 feat: specify effective canister id in provisional_create_canister_with_cycles
  CHANGELOG.md
  nix/sources.json
  src/dfx/assets/dfx-asset-sources.toml
  src/dfx/src/lib/environment.rs
  src/dfx/src/lib/identity/mod.rs
  src/dfx/src/lib/named_canister.rs
  src/dfx/src/lib/nns/install_nns.rs
  src/dfx/src/lib/operations/canister/create_canister.rs
  src/dfx/src/main.rs
  src/dfx/src/util/mod.rs
Labels: automerge-squash

#2808 chore: update Motoko to 0.7.4
  CHANGELOG.md
  nix/sources.json
  src/dfx/assets/dfx-asset-sources.toml
Labels: automerge-squash

#2809 fix: drop an additional step only run by ic-ref in asset canister tests
  e2e/tests-dfx/assetscanister.bash
Labels: automerge-squash

#2816 docs: add missing hyphens to force flag
  docs/cli-reference/dfx-identity.md
Labels: automerge-squash, cla:agreed

#2821 fix: for publish-manifest workflow failure starting 2022-12-12
  public/install/999_footer.sh
Labels: automerge-squash

#2818 fix: add retry logic to canister delete logic
  CHANGELOG.md
  src/dfx/src/commands/canister/delete.rs
Labels: automerge-squash

#2822 docs: document dfx start/replica --emulator
  docs/cli-reference/dfx-replica.md
  docs/cli-reference/dfx-start.md
Labels: automerge-squash

#2823 docs: add missing newline for dfx identity remove --drop-wallets
  docs/cli-reference/dfx-identity.md
Labels: automerge-squash

#2825 docs: remove repeated flags blocks
  docs/cli-reference/dfx-bootstrap.md
  docs/cli-reference/dfx-build.md
  docs/cli-reference/dfx-cache.md
  docs/cli-reference/dfx-canister.md
  docs/cli-reference/dfx-deploy.md
  docs/cli-reference/dfx-generate.md
  docs/cli-reference/dfx-identity.md
  docs/cli-reference/dfx-info.md
  docs/cli-reference/dfx-ledger.md
  docs/cli-reference/dfx-new.md
  docs/cli-reference/dfx-nns.md
  docs/cli-reference/dfx-ping.md
  docs/cli-reference/dfx-quickstart.md
  docs/cli-reference/dfx-replica.md
  docs/cli-reference/dfx-schema.md
  docs/cli-reference/dfx-sns.md
  docs/cli-reference/dfx-start.md
  docs/cli-reference/dfx-stop.md
  docs/cli-reference/dfx-upgrade.md
  docs/cli-reference/dfx-wallet.md
Labels: automerge-squash

#2828 docs: add entries for most top-level commands
  docs/cli-reference/dfx-parent.md
Labels: automerge-squash

#2829 fix: update replica binary urls
  nix/sources.json
  src/dfx/assets/dfx-asset-sources.toml
Labels: automerge-squash

#2832 docs: detail for canister update-settings --set-controller
  docs/cli-reference/dfx-canister.md
  src/dfx/src/commands/canister/update_settings.rs
Labels: automerge-squash

#2833 fix: Encode curve name in key imported from seed phrase
  e2e/tests-dfx/identity_command.bash
  src/dfx/src/lib/identity/mod.rs
Labels: automerge-squash

#2836 refactor: rename error enum names
  src/dfx/src/config/cache.rs
  src/dfx/src/lib/error/cache.rs
  src/dfx/src/lib/error/identity.rs
  src/dfx/src/lib/identity/identity_manager.rs
  src/dfx/src/lib/identity/mod.rs
Labels: automerge-squash

#2840 refactor: alphabetize IdentityError
  src/dfx/src/lib/error/identity.rs
Labels: automerge-squash
