Repository dfinity/sdk, pull requests merged in 2023-04, with the labels that each got.

#3000 test(frontend-canister): A basic upgrade load test
  e2e/tests-dfx/upgrade_assets_canister.bash
  e2e/utils/releases.bash
  scripts/workflows/e2e-matrix.py
Labels: automerge-squash, cla:agreed

#3070 fix: Revert basic upgrade load test
  e2e/tests-dfx/upgrade_assets_canister.bash
  e2e/utils/releases.bash
  scripts/workflows/e2e-matrix.py
Labels: automerge-squash

#3065 feat: dfx deploy --by-proposal
  CHANGELOG.md
  docs/cli-reference/dfx-deploy.md
  e2e/tests-dfx/assetscanister.bash
  src/canisters/frontend/ic-asset/src/asset/config.rs
  src/canisters/frontend/ic-asset/src/canister_api/methods/batch.rs
  src/canisters/frontend/ic-asset/src/canister_api/methods/method_names.rs
  src/canisters/frontend/ic-asset/src/canister_api/types/batch_upload/common.rs
  src/canisters/frontend/ic-asset/src/canister_api/types/batch_upload/v0.rs
  src/canisters/frontend/ic-asset/src/lib.rs
  src/canisters/frontend/ic-asset/src/sync.rs
  src/dfx/src/commands/deploy.rs
  src/dfx/src/lib/installers/assets/mod.rs
  src/dfx/src/lib/operations/canister/deploy_canisters.rs
Labels: automerge-squash

#3072 refactor(ic-asset): add Option to not upload chunks
  src/canisters/frontend/ic-asset/src/batch_upload/plumbing.rs
  src/canisters/frontend/ic-asset/src/sync.rs
  src/canisters/frontend/ic-asset/src/upload.rs
Labels: automerge-squash

#3073 refactor(ic-asset): assemble_commit_batch_arguments
  src/canisters/frontend/ic-asset/src/batch_upload/operations.rs
  src/canisters/frontend/ic-asset/src/sync.rs
  src/canisters/frontend/ic-asset/src/upload.rs
Labels: automerge-squash

#3078 chore: update to Motoko 0.8.7
  CHANGELOG.md
  nix/sources.json
  src/dfx/assets/dfx-asset-sources.toml
Labels: automerge-squash

#3083 docs: small typo in dfx-ledger.md
  docs/cli-reference/dfx-ledger.md
Labels: cla:agreed

#3085 fix: order batch operations to delete/remove data before create/add
  e2e/tests-dfx/assetscanister.bash
  src/canisters/frontend/ic-asset/src/canister_api/types/batch_upload/v0.rs
Labels: automerge-squash

#3077 fix!: require `--clean` when network config changes
  CHANGELOG.md
  e2e/tests-dfx/canister_http.bash
  e2e/tests-dfx/start.bash
  src/dfx-core/src/config/model/local_server_descriptor.rs
  src/dfx/src/commands/replica.rs
  src/dfx/src/commands/start.rs
  src/dfx/src/lib/replica_config.rs
Labels: automerge-squash

#3018 feat: ledger transfer optional set created_at_time field
  CHANGELOG.md
  docs/cli-reference/dfx-ledger.md
  e2e/tests-dfx/ledger.bash
  src/dfx/src/commands/ledger/create_canister.rs
  src/dfx/src/commands/ledger/mod.rs
  src/dfx/src/commands/ledger/top_up.rs
  src/dfx/src/commands/ledger/transfer.rs
  src/dfx/src/commands/quickstart.rs
Labels: automerge-squash, cla:agreed

#3088 refactor: immutable replica config and DRY --clean enforcement
  src/dfx/src/actors/mod.rs
  src/dfx/src/commands/replica.rs
  src/dfx/src/commands/start.rs
Labels: automerge-squash

#3094 fix: batches with computed evidence do not expire
  CHANGELOG.md
  src/canisters/frontend/ic-certified-assets/src/state_machine.rs
  src/canisters/frontend/ic-certified-assets/src/tests.rs
  src/distributed/assetstorage.wasm.gz
Labels: automerge-squash

#3099 test: use valid UTF-8 characters in rust nonstandard target dir test
  e2e/tests-dfx/rust.bash
Labels: automerge-squash

#3090 feat: expose `wasm-opt` optimizer in `ic-wasm` to users
  .github/workflows/publish.yml
  CHANGELOG.md
  Cargo.lock
  docs/dfx-json-schema.json
  e2e/assets/error_context/dfx.json
  e2e/tests-dfx/build.bash
  e2e/tests-dfx/error_context.bash
  src/dfx-core/src/config/model/dfinity.rs
  src/dfx/Cargo.toml
  src/dfx/src/lib/builders/custom.rs
  src/dfx/src/lib/builders/mod.rs
  src/dfx/src/lib/builders/motoko.rs
  src/dfx/src/lib/builders/rust.rs
  src/dfx/src/lib/canister_info.rs
  src/dfx/src/lib/models/canister.rs
Labels: automerge-squash

#3098 chore: Bundle btc canister
  CHANGELOG.md
  nix/sources.json
  scripts/write-dfx-asset-sources.sh
  src/dfx/assets/build.rs
  src/dfx/assets/dfx-asset-sources.toml
  src/dfx/assets/prepare_assets.rs
  src/dfx/src/util/assets.rs
Labels: automerge-squash

#3102 docs: fix link to cycles wallet repo
  src/distributed/README.md
Labels: automerge-squash, cla:agreed

#3101 fix: Stop `dfx deploy` from creating a wallet if all canisters exist
  CHANGELOG.md
  e2e/tests-dfx/deploy.bash
  src/dfx/src/commands/deploy.rs
  src/dfx/src/lib/operations/canister/deploy_canisters.rs
Labels: automerge-squash

#3105 chore: update changelog for dfx 0.14.0
  CHANGELOG.md
Labels: automerge-squash

#3106 docs: fix mismatched triple-quote and disambiguate new convention
  docs/migration/dfx-0.14.0-migration-guide.md
Labels: automerge-squash

#3093 fix: dfx generate no longer requires canister IDs for Motoko canisters
  CHANGELOG.md
  e2e/tests-dfx/generate.bash
  e2e/tests-dfx/remote.bash
  src/dfx/src/commands/generate.rs
Labels: automerge-squash

#3111 chore: promote dfx 0.14.0
  Cargo.lock
  public/manifest.json
  src/dfx/Cargo.toml
Labels: automerge-squash

#3114 fix: split up asset synchronization batches in order not to exceed the per-message instruction limit
  CHANGELOG.md
  Cargo.lock
  src/canisters/frontend/ic-asset/Cargo.toml
  src/canisters/frontend/ic-asset/src/canister_api/types/asset.rs
  src/canisters/frontend/ic-asset/src/canister_api/types/batch_upload/common.rs
  src/canisters/frontend/ic-asset/src/canister_api/types/batch_upload/v1.rs
  src/canisters/frontend/ic-asset/src/sync.rs
Labels: automerge-squash
